name: Automation

on:
  push:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semgrep (Code Scan)
        uses: semgrep/semgrep-action@v1
        continue-on-error: true
        with:
          config: p/owasp-top-ten

      - name: Build Docker Image
        run: docker build -t devsecops-app .

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: devsecops-app

      - name: Run Application
        run: docker run -d -p 5000:5000 devsecops-app

      - name: ZAP DAST Scan
        uses: zaproxy/action-baseline@v0.10.0
        continue-on-error: true
        with:
          target: "http://localhost:5000"
