name: DevSecOps Beginner Pipeline with Reports

on:
  push:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # --------------------
      # Semgrep SAST Report
      # --------------------
      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep and generate SARIF report
        run: semgrep --config p/owasp-top-ten --sarif --output semgrep.sarif .
        continue-on-error: true

      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep.sarif

      # --------------------
      # Build Docker Image
      # --------------------
      - name: Build Docker Image
        run: docker build -t devsecops-app .

      # --------------------
      # Trivy Image Report
      # --------------------
      - name: Trivy Image Scan (JSON report)
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: devsecops-app
          format: json
          output: trivy-report.json

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json

      # --------------------
      # ZAP DAST Report
      # --------------------

      - name: Run Application Container
        run: docker run -d -p 5000:5000 devsecops-app

      - name: Wait for application to be ready
        run: sleep 15

      - name: ZAP Baseline Scan (HTML report)
        uses: zaproxy/action-baseline@v0.10.0
        continue-on-error: true
        with:
          target: "http://localhost:5000"
          cmd_options: "-r zap-report.html"

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: zap-report
          path: zap-report.html
